/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg2;

/**
 *
 * @author Jonny
 */
public class Main {
//  
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  /**
   * @param args the command line arguments
   */
  public static void main(String[] args) {
    int currentFib = 2;
    int previousFib = 1;
    int ans = 0;
    int nextFib;
    while (currentFib < 4000000) {
      if(currentFib % 2 == 0){
        ans += currentFib;
      }
      nextFib = currentFib + previousFib;
      previousFib = currentFib;
      currentFib = nextFib;
    }
    System.out.println(ans);
  }
}
